# CLion remote docker environment (How to build docker container, run and stop it)
#
# Build and run:
#   docker build -t repository:tag .
#   docker run -d --cap-add sys_ptrace -p 127.0.0.1:2222:22 --name container_name image_name
#   ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:2222"
#
# stop:
#   docker stop container_name
#
# ssh credentials (test user):
#   user@password

FROM rudrivas/cpp_docker_environment:latest

WORKDIR /autograder/

CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config_test_clion"]
